### ISSUE TITLE
Can the identifier flag for form fields from the data dictionary be included in the output?

### ISSUE THREAD

**Issue by targetpharma** [IUREDCap/redcap-etl-module#17]
## Background

The Online Designer for REDCap allows a field to be flagged as containing identifying information: 

![image](https://user-images.githubusercontent.com/20141935/81332859-b6c09500-9071-11ea-94f8-98866d2edd50.png)

This `identifier` flag shows up in the data dictionary when making the following type of API call:

```
data = {
    'token': 'API TOKEN',
    'content': 'metadata',
    'format': 'json',
    'returnFormat': 'json'
}
```

Snippet of output for a single field:

```
{
    "branching_logic": "",
    "custom_alignment": "",
    "field_annotation": "",
    "field_label": "First Name ",
    "field_name": "first_name",
    "field_note": "",
    "field_type": "text",
    "form_name": "pro_consent_email_address",
    "identifier": "y",
...
}
```

## Request for Enhancement

Would it be possible to include a way to get field level metadata included in an export from REDCap-ETL? Note, my particular interest is the `identifier` flag, and I am not sure how valuable other metadata would be to anyone else.

The use case is that we'd like our downstream database to be able to control access to PHI fields by using information derived from this `identifier` flag.

There is not enough information for me to tell if this request is a part of https://github.com/IUREDCap/redcap-etl-module/issues/4. For that issue, I am not sure what is meant exactly by "lookup table".

**Comment by mullen2** [comment]
I can't think of a reason why this couldn't be done, and it sounds like a great idea to me.

In addition to a REDCap metadata table, there would need to be a table that maps database fields to REDCap fields, since the field names can be changed when the data is exported. Or, all that information could be combined into a single table, which would be easier to work with, but at the cost of creating some possible data redundancy (if the same REDCap field was exported to multiple tables). A table with the following fields could be added:
- table name
- field name
- REDCap field name
- identifier
- other REDCap metadata...

I'll look into this.

The "lookup table" maps multiple choice values to labels.

**Comment by mullen2** [comment]
@targetpharma This has finally been released. There is a new table redcap_metadata that is automatically generated that maps database fields to their corresponding REDCap fields, and has a flag that indicates if the field is an identifier in REDCap.
