### ISSUE TITLE
Deprecated error message using redcap-etl with php >= 8.1

### ISSUE THREAD

**Issue by ogranert** [IUREDCap/redcap-etl-module#42]
Installing the ETL Module (REDCap-ETL Module 2.4.5) in RedCap running with php/8.1 produce the following error messages:
"
Error message: Warning - Trying to access array offset on value of type null, File: .../redcap/modules/redcap_etl_module_v2.4.5/classes/Settings.php, Line: 1167

Error message: Deprecated - Return type of IU\RedCapEtlModule\Workflows::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice, File: .../redcap/modules/redcap_etl_module_v2.4.5/classes/Workflows.php, Line: 20
"
Note: The last problem can probably be solved (temporary) using the following advice from stackoverflow:
https://stackoverflow.com/questions/70446612/how-do-i-solve-this-jsonserializable-error-right-after-i-logged-in-using-azure

Best
Oliver

**Comment by mullen2** [comment]
@ogranert Thanks for yout feedback.

The warning message does appear to be caused by a bug, but one that only occurs in the REDCap-ETL external module's initial state. And, from testing that I did, it looks like the bug should not prevent REDCap-ETL from functioning correctly. I have made a fix for this in the code, which will go out in the next release.

The cause of the deprecation message is a known issue. We are still supporintg PHP 7, and to fix the deprecation issue correctly for PHP 8, we would need to break compatibility with PHP 7. My expectation is that we will drop support for PHP 7 some time next year (2025), and fix this issue at that time. This issue should also not prevent REDCap-ETL from functioning correctly.

**Comment by ogranert** [comment]
@mullen2 : Thank you very much for your fast reply and the code fix!

I know it`s not the final solution, but the deprecation message in php 8.1 can be suppressed by adding the "#[ReturnTypeWillChange]" attribute as described by the stackoverflow post. 

PHP versions prior to 8.0 parses the attribute syntax as a code comment, and does not cause any syntax errors.
(see https://php.watch/versions/8.1/ReturnTypeWillChange)
